/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examquestion2;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class MovieTicket extends javax.swing.JFrame {

    /**
     * Creates new form MovieTicket
     */
    public MovieTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMovie = new javax.swing.JLabel();
        lblnumberOftickets = new javax.swing.JLabel();
        lblticketPrice = new javax.swing.JLabel();
        lblticketReport = new javax.swing.JLabel();
        cbMovies = new javax.swing.JComboBox<>();
        InputTickets = new javax.swing.JTextField();
        InputTicketPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        clearMenu = new javax.swing.JMenu();
        processMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMovie.setText("MOVIE:");

        lblnumberOftickets.setText("NUMBER OF TICKETS:");

        lblticketPrice.setText("TICKET PRICE:");

        lblticketReport.setText("TICKET REPORT:");

        cbMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napoleon", "Oppenheimer", "Damsel", " " }));

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        jMenu1.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        mainMenu.add(jMenu1);

        clearMenu.setText("Tools");

        processMenu.setText("Process");
        processMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMenuActionPerformed(evt);
            }
        });
        clearMenu.add(processMenu);

        jMenuItem2.setText("Clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        clearMenu.add(jMenuItem2);

        mainMenu.add(clearMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnumberOftickets, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblticketReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblticketPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMovies, 0, 163, Short.MAX_VALUE)
                            .addComponent(InputTickets)
                            .addComponent(InputTicketPrice))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie)
                    .addComponent(cbMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumberOftickets)
                    .addComponent(InputTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblticketPrice)
                    .addComponent(InputTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblticketReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
         int confirmed = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to exit?", "Exit Confirmation",
        JOptionPane.YES_NO_OPTION);

       if (confirmed == JOptionPane.YES_OPTION) {
        System.exit(0);  // Stop the application if the user confirms
    }
    }//GEN-LAST:event_exitMenuActionPerformed

    private void processMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMenuActionPerformed
     if (!validateInput()) {
        return;  // Exit if validation fails
    }
    String Movie = (String) cbMovies.getSelectedItem();
    String Tickets = InputTickets.getText();
    
    try {
        double ticketPrice = Double.parseDouble(InputTicketPrice.getText());
         double numberOftickets = Double.parseDouble(InputTickets.getText());
        
        // Calculate the technician’s commission
        double totalCost = ticketPrice/100 * numberOftickets * (100+14);
        
        String report = " MOVIE TICKET REPORT " + 
                         "\n"+
                        "\n. MOVIE NAME: " + Movie +
                        "\n. MOVIE TICKET PRICE: " + ticketPrice +
                        "\n. NUMBER OF TICKETS: " + Tickets + 
                        "\n. TOTAL TICKET PRICE: " + totalCost;
        
         // Display the formatted report in the output field
        outputArea.setText(report);
        
        } catch (NumberFormatException e) {
        // Handle any number format exceptions for ticketCost 
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for ticket cost.");
    }
     try (FileWriter writer = new FileWriter("report.txt")) {
        String reportText = outputArea.getText();
        System.out.println(reportText);  // Temporary check
        writer.write(reportText);
        JOptionPane.showMessageDialog(this, "Report saved successfully!");
    } catch (IOException e) 
    {
        JOptionPane.showMessageDialog(this, "Error saving report: " + e.getMessage());
    }
    }//GEN-LAST:event_processMenuActionPerformed
 private boolean validateInput() {
    // Check if Tickets and name fields are filled
    if (cbMovies.getSelectedItem() == null || InputTickets.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in the Movie and Tickets.");
        return false;
    }
    
    try {
       double ticketPrice = Double.parseDouble(InputTicketPrice.getText());
  
        
        // Check if repair cost and rate are positive
        if (ticketPrice <= 0 || 14 <= 0) {
            JOptionPane.showMessageDialog(this, "Repair Cost and Rate must be greater than zero.");
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Repair Cost and Rate.");
        return false;
    }
    
    // All validations passed
    return true;
}
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    cbMovies.setSelectedIndex(0);  // Reset the location combo box to the first item
    InputTickets.setText("");            // Clear the number of tickets  field
    InputTicketPrice.setText("");            // Clear the ticket cost field
    outputArea.setText("");            // Clear the technician output field
  
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputTicketPrice;
    private javax.swing.JTextField InputTickets;
    private javax.swing.JComboBox<String> cbMovies;
    private javax.swing.JMenu clearMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblnumberOftickets;
    private javax.swing.JLabel lblticketPrice;
    private javax.swing.JLabel lblticketReport;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JMenuItem processMenu;
    // End of variables declaration//GEN-END:variables
}
